GET http://localhost:8080/api/v1/exchanger/EUR
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/v1/exchanger
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/v1/exchanger/request
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/v1/exchanger/request/156
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8080/api/v1/exchanger/request/shutDownContext
Accept: application/json
Content-Type: application/json

###

DELETE http://localhost:8080/api/v1/exchanger/request/delete/+380968443448
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/v1/exchanger/request/report
Accept: application/json
Content-Type: application/json

###


GET http://localhost:8080/api/v1/exchanger/request/report/2021-04-02/2021-04-10/USD
Accept: application/json
Content-Type: application/json

###